version: '3.4'

services:
  server:
    container_name: heroes
    build: docker/server
    ports:
      - 8090:8090
      - 5858:5858
    volumes:
      - ./:/var/www/heroes
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    tty: true
    command: /docker-entrypoint.sh
    depends_on:
      - mongodb
    networks:
      - heroes-network

  mongodb:
    image: mongo:latest
    container_name: heroes-mongodb
    ports:
      - 27017:27017
    networks:
      -  heroes-network

networks:
  heroes-network:
    external: true


    # mongodb://mongodb:27017/wosido